name: 'PROYECTO'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


# MATERIALIZAR COMO VIEW
    # - Frecuencia de actualización alta
    # - Bajo volumen de datos
    # - Sin necesidad de persistencia

    # - Generalmente, las capas de staging contienen datos en bruto o ligeramente transformados que se utilizan para preparaciones y transformaciones adicionales. 
    # Dado que las transformaciones finales aún no se han aplicado, es recomendable materializar estas capas como vistas.


# MATERIALIZAR COMO TABLE
    # - Rendimiento
    # - Datos estables
    # - Necesidad de persistencia
    
    # - Las capas intermediate y de analytics generalmente contienen datos transformados y listos para el análisis. 
    # Estas capas pueden beneficiarse de la materialización en tablas para mejorar el rendimiento y la eficiencia de las consultas.

models:
  PROYECTO:
    intermediate:
      materialized: table
      +database: PROYECTO
    staging:
      materialized: view
      +database: PROYECTO

vars:
  database: 'RAW'
  schema: 'adrian_brais_samuel__schema'

seeds:
  PROYECTO:
    enabled: true